export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_RESISTER_FAIL = 'USER_RESISTER_FAIL';
export const USER_RESISTER_REQUEST = 'USER_RESISTER_REQUEST';
export const USER_RESISTER_SUCCESS = 'USER_RESISTER_SUCCESS';